sudo: false
language: node_js
node_js:
  - "4"
  - "5"
script:
  - "npm run travis"
  - "npm run travisServer"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  irc:
    channels:
      - "irc.hackint.eu#subtitles"
    on_success: change
    on_failure: change
  email: false
